version: 2

sources:
  - name: census_staging
    schema: staging
    tables:
      - name: census_2010_ent_prepared
        meta:
          dagster:
            asset_key: ["staging", "2010", "ent"]

      - name: census_2010_mun_prepared
        meta:
          dagster:
            asset_key: ["staging", "2010", "mun"]

      - name: census_2010_ageb_prepared
        meta:
          dagster:
            asset_key: ["staging", "2010", "ageb"]

      - name: denue_2020_11_prepared
        meta:
          dagster:
            asset_key: ["staging", "denue", "2020_11"]

      - name: denue_2021_11_prepared
        meta:
          dagster:
            asset_key: ["staging", "denue", "2021_11"]

      - name: denue_2022_11_prepared
        meta:
          dagster:
            asset_key: ["staging", "denue", "2022_11"]

      - name: denue_2023_11_prepared
        meta:
          dagster:
            asset_key: ["staging", "denue", "2023_11"]

      - name: denue_2024_11_prepared
        meta:
          dagster:
            asset_key: ["staging", "denue", "2024_11"]

      - name: denue_2025_05_prepared
        meta:
          dagster:
            asset_key: ["staging", "denue", "2025_05"]

  - name: published_inputs
    schema: public
    tables:
      - name: metropoli_2020
        meta:
          dagster:
            asset_key: ["metropoli", "2020"]
